import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

public class DatabaseWorker {
    private final Database database;

    // Generated by the reading stage.
    //------------------------------------------------------------------------
    public List<Article> processedArticles = new ArrayList<>();
    
    // Generated by the indexing stage.
    //------------------------------------------------------------------------
    public HashMap<String, List<String>> languagePublishedArticles = new HashMap<>();
    public HashMap<String, List<String>> categoryPublishedArticles = new HashMap<>();
    public HashMap<String, Integer> authorPublishedCount = new HashMap<>();
    public HashMap<String, Integer> englishWordCount = new HashMap<>();

    public DatabaseWorker(Database inDatabase) {
        database = inDatabase;
    }

    @SuppressWarnings("CallToPrintStackTrace")
    public void run() {
        try {
            database.waitForStartingToReadArticles();
            String metadataFilePath = database.acquireMetadataFilePath();
            while (metadataFilePath != null) {
                // Read articles metadatas from the given file.
                readArticleMetadataFromFile(metadataFilePath);

                // Get a new metadata filepath.
                metadataFilePath = database.acquireMetadataFilePath();
            }
            database.decrementNumberOfWorkersReading();
            
            database.waitForStartingToIndexArticles();
            Article articleToIndex = database.acquireArticleToIndex();
            while (articleToIndex != null) {
                // Index the article.
                indexArticle(articleToIndex);

                // Get a new article.
                articleToIndex = database.acquireArticleToIndex();
            }
            database.decrementNumberOfWorkersIndexing();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    @SuppressWarnings("CallToPrintStackTrace")
    private void readArticleMetadataFromFile(String filePath) {
        List<Article> articles = new ArrayList<>();
        try {
            ObjectMapper mapper = new ObjectMapper();
            mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            articles = mapper.readValue(
                    new File(filePath),
                    new TypeReference<List<Article>>() {}
            );
        } catch (IOException e) {
            e.printStackTrace();
        }

        processedArticles.addAll(articles);
    }

    private void indexArticle(Article article) {
        // Author.
        int currentAuthorPublishedCount = authorPublishedCount.getOrDefault(article.author, 0);
        authorPublishedCount.put(article.author, currentAuthorPublishedCount + 1);

        // Language.
        if (database.getInputs().languages.contains(article.language)) {
            languagePublishedArticles.putIfAbsent(article.language, new ArrayList<>());
            languagePublishedArticles.get(article.language).add(article.uuid);
        }

        // Categories.
        for (String category : article.categories) {
            if (database.getInputs().categories.contains(category)) {
                categoryPublishedArticles.putIfAbsent(category, new ArrayList<>());
                categoryPublishedArticles.get(category).add(article.uuid);
            }
        }

        // Keywords.
        if (article.language.equals("english")) {
            String[] rawTextWords = article.text.toLowerCase().split("\\s+");
            HashSet<String> textWords = new HashSet<>();
            for (String rawTextWord : rawTextWords) {
                String textWord = rawTextWord.replaceAll("[^a-z]", "");
                if (!textWord.isEmpty() && !database.getInputs().englishLinkingWords.contains(textWord))
                    textWords.add(textWord);
            }
            for (String textWord : textWords) {
                int currentCount = englishWordCount.getOrDefault(textWord, 0);
                englishWordCount.put(textWord, currentCount + 1);
            }
        }
    }
}
